# Chapter 01: Vectors, Matrices, and Arrays


## 1.1 Creating a Vector

In [5]:
# load library
import numpy as np

# create a vector as a row
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1],[2],[3]])
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


## 1.2 Creating a Matrix

In [ ]:
matrix = np.array([[1, 2], [1, 2], [1, 2]])
print(matrix)


[[1 2]
 [1 2]
 [1 2]]


## 1.3 Creating a Sparse Matrix

In [ ]:
from scipy import sparse

matrix = np.array([[0, 0], [0, 1], [3, 0]])
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements
You need to select one or more elements in a vector or matrix.

In [11]:
vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select third element of vector
print(vector[2])

# Select third element of vector
print(matrix[1,1])

3
5


In [15]:
# select all elements of a vector
print(vector[:])

#select everything up to and inlcuding the third element
print(vector[:3])

# select eveything after the third element
print(vector[3:])

# select the last element
print(vector[-1])

# select the first two rows and all columns of a matrix
print(matrix[:2,:])

# select all rows and the second column
print(matrix[:,1:2])

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]
